### ISSUE TITLE
Logo in email (when using email connector) is HUGE/doesn't load

### ISSUE THREAD

**Issue by xetnez** [tier2tickets/Feedback#21]
There is a huge gap from the top of the email to where it says "View report". The logo doesn't display in outlook, but if you view the email in a browser the logo is gigantic.

**Comment by xetnez** [comment]
follow-up: I see this is fixed now.

**Comment by grintor** [comment]
I think this might have just been some css failing to load at some point. Thanks for letting us know it's fixed!
