### ISSUE TITLE
Long Instructions in Step 1 breaks layout

### ISSUE THREAD

**Issue by pmfjoe** [tier2tickets/Feedback#22]
Having more than 40 or so characters in the Step 1 Instructions field breaks the layout of Step 1.

Unbroken: https://imgur.com/a/cSZi3e6

Broken: https://imgur.com/a/YYCXu9C

**Comment by grintor** [comment]
Thanks for letting us know! We will try to get that fixed soon.

**Comment by elcopeland** [comment]
Hey there @pmfjoe, apologies for the delay, we cleaned this up a few versions ago and just forgot to close out our issues here! 

You should now be able to drop a significant amount of text on that first page: 
![Screen Shot 2020-05-20 at 4 37 36 PM](https://user-images.githubusercontent.com/22402707/82494851-3a3da580-9ab8-11ea-8ebb-e90247b9cd68.png)
