### ISSUE TITLE
Connectwise: Hide Ticket Link

### ISSUE THREAD

**Issue by elcopeland** [tier2tickets/Feedback#23]
> CW integration put the information in the ticket, instead of just the link to the report. My preference is that I would prefer if my customer not be able to click the link. Perhaps their description in the ticket, and the body of the information in an internal note?

**Comment by grintor** [comment]
I agree with this. We will get it done soon. Thanks

**Comment by grintor** [comment]
This is done. We have moved the link into an internal note
