### ISSUE TITLE
MFA is a MUST

### ISSUE THREAD

**Issue by kingsolmn** [tier2tickets/Feedback#29]
Limiting account access through a 2FA/MFA method is a must for any service/tool like this. I haven't seen anything like this on the roadmap. Having an SMS based MFA as a backup is ok, but a true ToTP MFA method must be a priority before leaving BETA status (personally, I'd prefer ToTP MFA in the next milestone/release).

Anyway, this is a great service for MSPs and I don't want to hear about it being an attack vector in the news.

Thanks for all you do!

**Comment by apermenter** [comment]
MFA is in progress right now.  We had hoped it would be ready by our beta release but it is tied to setting up sub-accounts which is taking a little longer.  We hope to have this available very soon.
