### ISSUE TITLE
Splash screen placement is a little wonky

### ISSUE THREAD

**Issue by grintor** [tier2tickets/Feedback#3]
Splash screen placement is a little wonky, then again I have a weird monitor setup but it is snapping to the very center of my 4 monitors rather than to the middle of my primary monitor? Very minor thing to fix I’m sure.

**Comment by pmfjoe** [comment]
I had this too, the Window snapped right in the middle of my two screens.

**Comment by grintor** [comment]
I think this is fixed in 0.3.28. Give it a try and re-open this if not
