### ISSUE TITLE
Long Issue Descriptions Break Layout

### ISSUE THREAD

**Issue by masseym** [tier2tickets/Feedback#34]
I tried entering a LOT of text in the issue description.  On the review page, it pushes everything beyond the end of the form.  Possible make that last screen a scrollable window.

**Comment by grintor** [comment]
Good feedback, we'll do that. Thanks!

**Comment by elcopeland** [comment]
Fixed a while ago and forgot to close, apologies! 

![Screen Shot 2020-05-20 at 3 14 35 PM](https://user-images.githubusercontent.com/22402707/82487776-dc579080-9aac-11ea-9057-a03002653a2e.png)
![Screen Shot 2020-05-20 at 3 15 41 PM](https://user-images.githubusercontent.com/22402707/82487778-dc579080-9aac-11ea-8b73-f02929792eea.png)
