### ISSUE TITLE
2FA resets to disabled

### ISSUE THREAD

**Issue by xetnez** [tier2tickets/Feedback#42]
This is the second time that 2FA has been reset to disabled for me. I'm not turning it off, and I'm the only one at the company with login info.

I use Authy, Chrome, & lastpass when I interact with HDB.

**Comment by grintor** [comment]
Sorry for the trouble. We were doing some work on that part of the code which caused that to happen. has it happened any more since you put in this report?

**Comment by xetnez** [comment]
It has not. (I wanted to give some times before I replied to make sure)
