### ISSUE TITLE
Window Opens Across 2 Screens

### ISSUE THREAD

**Issue by Raymoz101** [tier2tickets/Feedback#43]
Hi there,

We've just setup our test buttons and really enjoying it!

On my PC alone when I hit my button the splash screen is across 2 screens and once the information has been collected the next window also opens across 2 screens and I drag it into the middle of my main monitor.

1st = 1080P res. laptop screen at 150% scaling
2nd = 1080P 100% scaling monitor
3rd = 1080P 100% scaling monitor

The splash screen and window opens across the laptop screen and monitor 2.

On my colleagues laptop who has the same setup, but 100% scaling on all 3 screens, the windows all behave as normal and are in the center of his main screen.

It appears as though having the scaling is the issue, which is possibly going to be an intermittent issue depending on how users have their screens setup.

Kind regards,
Ray

**Comment by grintor** [comment]
Thank you for the great bug report! I am going to try and focus on this bug today and get it ironed out. I will let you know when I have a new build for you to try

**Comment by grintor** [comment]
I think this is fixed in 0.3.28. Give it a try and re-open this if not
