### ISSUE TITLE
Auto-Update to 0.5.x.7 lost custom iconname; reset Desktop icon to Helpdesk Button

### ISSUE THREAD

**Issue by justinswall** [tier2tickets/Feedback#52]
Upon initial installation of the software we used the WRAPPED_ARGUMENTS to set a custom iconname.  During the auto-update procedure however, the icon was changed back to Helpdesk Button.  There should be a way to keep customization upon auto-update.

**Comment by grintor** [comment]
Thanks for letting us know about this issue. It was fixed in newest version.

Chris
