### ISSUE TITLE
UI does not handle zoomed screens

### ISSUE THREAD

**Issue by chavousc** [tier2tickets/Feedback#56]
On "zoomed" screens - IE screens where "Make everything bigger" is turned on in display settings (the *NORM* for many laptops, MS surface devices, etc) the UI is distorted:

**Comment by grintor** [comment]
Thanks for reporting this. We have it fixed in 0.6.x.3 and I gave you credit in the changelog https://docs.tier2tickets.com/content/general/changelog/#0.6.3
