### ISSUE TITLE
Submission Error with Freshservice

### ISSUE THREAD

**Issue by thiggin** [tier2tickets/Feedback#57]
Not sure when it started but we are now getting a submission error with Freshservice.
![image](https://user-images.githubusercontent.com/16546032/103562059-15981180-4e80-11eb-89e5-95da74ac9377.png)

The ticket source "Helpdesk Button" is a valid option in the system.
I have also tried with a new source "HDButton" to see if the space was causing the error but receive the same error.

**Comment by TheGreatTSBob** [comment]
Unfortunately, this is a limitation of the PSA's API. The source list in Freshservice is not something available to the API. Currently, the V1 (stable) API shows this mapping for the ticket source and no way to obtain the list of any custom sources. Additionally, the sources are listed in the ticket data by number, not by name, so there is no way for us to even allow custom sources from our side.
