### ISSUE TITLE
mass communication

### ISSUE THREAD

**Issue by grintor** [tier2tickets/Feedback#6]
this is another bottom-of-the-pile thing that, despite not having needed/used it yet, I really like the idea of having, and that is this: mass communication. Being able to send an alert that not only hits everyone as a Windows notification/toast message but also pushes to android/ios app as a notification to communicate major outages or other important things is a really slick thing I’d miss from our current solution. Again I’d say its not your primary goal or anything but considering where and how you will be implemented, your app puts itself in a position where having this feature would be far reaching in this area, and that’s nice.

**Comment by pmfjoe** [comment]
As long as you could somehow filter the agents by company/customer.

**Comment by apermenter** [comment]
I feel like this has too much overlap with a lot of the RMM tools out there already, it's kind of a big task also.  we are going to table this until we get further along.
