### ISSUE TITLE
Desktop Icon

### ISSUE THREAD

**Issue by texomans** [tier2tickets/Feedback#69]
We tested the first install on a machine to see how it worked exactly. Now, we have configured everything in branding, integrations, etc. However, the desktop icon will not change to the new icon that we uploaded. We have tried uploading it as PNG and ICO. Neither worked. They do show in the web console, but will not apply to desktop icon even after uninstall, reinstall, reboot after each uninstall/reinstall. Not sure what else to try.

The taskbar icon works fine.

**Comment by TheGreatTSBob** [comment]
i think this was resolved in an email exchange.
